apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test1
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-test1
  template:
    metadata:
      labels:
        app: k8s-test1
    spec:
      containers:
        - name: k8s-test1
          image: ${IMAGE_NAME}:${IMAGE_TAG}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: file-storage
              mountPath: /app/data
      volumes:
        - name: file-storage
          persistentVolumeClaim:
            claimName: app-pvc
